// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// CheckCronReader is a Reader for the CheckCron structure.
type CheckCronReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckCronReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckCronOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/checkCron] CheckCron", response, response.Code())
	}
}

// NewCheckCronOK creates a CheckCronOK with default headers values
func NewCheckCronOK() *CheckCronOK {
	return &CheckCronOK{}
}

/*
CheckCronOK describes a response with status code 200, with default header values.

ok
*/
type CheckCronOK struct {
	Payload *models.DevopsCheckCronRes
}

// IsSuccess returns true when this check cron o k response has a 2xx status code
func (o *CheckCronOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check cron o k response has a 3xx status code
func (o *CheckCronOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check cron o k response has a 4xx status code
func (o *CheckCronOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check cron o k response has a 5xx status code
func (o *CheckCronOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check cron o k response a status code equal to that given
func (o *CheckCronOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check cron o k response
func (o *CheckCronOK) Code() int {
	return 200
}

func (o *CheckCronOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/checkCron][%d] checkCronOK %s", 200, payload)
}

func (o *CheckCronOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/checkCron][%d] checkCronOK %s", 200, payload)
}

func (o *CheckCronOK) GetPayload() *models.DevopsCheckCronRes {
	return o.Payload
}

func (o *CheckCronOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DevopsCheckCronRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
