// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// DeletePipelineReader is a Reader for the DeletePipeline structure.
type DeletePipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/pipelines/{pipeline}] DeletePipeline", response, response.Code())
	}
}

// NewDeletePipelineOK creates a DeletePipelineOK with default headers values
func NewDeletePipelineOK() *DeletePipelineOK {
	return &DeletePipelineOK{}
}

/*
DeletePipelineOK describes a response with status code 200, with default header values.

ok
*/
type DeletePipelineOK struct {
	Payload *models.V1alpha3Pipeline
}

// IsSuccess returns true when this delete pipeline o k response has a 2xx status code
func (o *DeletePipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete pipeline o k response has a 3xx status code
func (o *DeletePipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pipeline o k response has a 4xx status code
func (o *DeletePipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete pipeline o k response has a 5xx status code
func (o *DeletePipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete pipeline o k response a status code equal to that given
func (o *DeletePipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete pipeline o k response
func (o *DeletePipelineOK) Code() int {
	return 200
}

func (o *DeletePipelineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/pipelines/{pipeline}][%d] deletePipelineOK %s", 200, payload)
}

func (o *DeletePipelineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/pipelines/{pipeline}][%d] deletePipelineOK %s", 200, payload)
}

func (o *DeletePipelineOK) GetPayload() *models.V1alpha3Pipeline {
	return o.Payload
}

func (o *DeletePipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha3Pipeline)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
