// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetConsoleLogReader is a Reader for the GetConsoleLog structure.
type GetConsoleLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConsoleLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConsoleLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/consolelog] GetConsoleLog", response, response.Code())
	}
}

// NewGetConsoleLogOK creates a GetConsoleLogOK with default headers values
func NewGetConsoleLogOK() *GetConsoleLogOK {
	return &GetConsoleLogOK{}
}

/*
GetConsoleLogOK describes a response with status code 200, with default header values.

OK
*/
type GetConsoleLogOK struct {
}

// IsSuccess returns true when this get console log o k response has a 2xx status code
func (o *GetConsoleLogOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get console log o k response has a 3xx status code
func (o *GetConsoleLogOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get console log o k response has a 4xx status code
func (o *GetConsoleLogOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get console log o k response has a 5xx status code
func (o *GetConsoleLogOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get console log o k response a status code equal to that given
func (o *GetConsoleLogOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get console log o k response
func (o *GetConsoleLogOK) Code() int {
	return 200
}

func (o *GetConsoleLogOK) Error() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/consolelog][%d] getConsoleLogOK", 200)
}

func (o *GetConsoleLogOK) String() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/consolelog][%d] getConsoleLogOK", 200)
}

func (o *GetConsoleLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
