// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBranchPipelineRunNodesParams creates a new GetBranchPipelineRunNodesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBranchPipelineRunNodesParams() *GetBranchPipelineRunNodesParams {
	return &GetBranchPipelineRunNodesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBranchPipelineRunNodesParamsWithTimeout creates a new GetBranchPipelineRunNodesParams object
// with the ability to set a timeout on a request.
func NewGetBranchPipelineRunNodesParamsWithTimeout(timeout time.Duration) *GetBranchPipelineRunNodesParams {
	return &GetBranchPipelineRunNodesParams{
		timeout: timeout,
	}
}

// NewGetBranchPipelineRunNodesParamsWithContext creates a new GetBranchPipelineRunNodesParams object
// with the ability to set a context for a request.
func NewGetBranchPipelineRunNodesParamsWithContext(ctx context.Context) *GetBranchPipelineRunNodesParams {
	return &GetBranchPipelineRunNodesParams{
		Context: ctx,
	}
}

// NewGetBranchPipelineRunNodesParamsWithHTTPClient creates a new GetBranchPipelineRunNodesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBranchPipelineRunNodesParamsWithHTTPClient(client *http.Client) *GetBranchPipelineRunNodesParams {
	return &GetBranchPipelineRunNodesParams{
		HTTPClient: client,
	}
}

/*
GetBranchPipelineRunNodesParams contains all the parameters to send to the API endpoint

	for the get branch pipeline run nodes operation.

	Typically these are written to a http.Request.
*/
type GetBranchPipelineRunNodesParams struct {

	/* Branch.

	   the name of branch, same as repository branch.
	*/
	Branch string

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Limit.

	   the limit item count of the search.

	   Format: limit=%d
	   Default: "limit=10000"
	*/
	Limit *string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run id, the unique id for a pipeline once build.
	*/
	Run string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get branch pipeline run nodes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchPipelineRunNodesParams) WithDefaults() *GetBranchPipelineRunNodesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get branch pipeline run nodes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchPipelineRunNodesParams) SetDefaults() {
	var (
		limitDefault = string("limit=10000")
	)

	val := GetBranchPipelineRunNodesParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithTimeout(timeout time.Duration) *GetBranchPipelineRunNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithContext(ctx context.Context) *GetBranchPipelineRunNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithHTTPClient(client *http.Client) *GetBranchPipelineRunNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithBranch(branch string) *GetBranchPipelineRunNodesParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDevops adds the devops to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithDevops(devops string) *GetBranchPipelineRunNodesParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithLimit adds the limit to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithLimit(limit *string) *GetBranchPipelineRunNodesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithPipeline adds the pipeline to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithPipeline(pipeline string) *GetBranchPipelineRunNodesParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) WithRun(run string) *GetBranchPipelineRunNodesParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the get branch pipeline run nodes params
func (o *GetBranchPipelineRunNodesParams) SetRun(run string) {
	o.Run = run
}

// WriteToRequest writes these params to a swagger request
func (o *GetBranchPipelineRunNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
