// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// GetPipelineRunNodesReader is a Reader for the GetPipelineRunNodes structure.
type GetPipelineRunNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineRunNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineRunNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes] GetPipelineRunNodes", response, response.Code())
	}
}

// NewGetPipelineRunNodesOK creates a GetPipelineRunNodesOK with default headers values
func NewGetPipelineRunNodesOK() *GetPipelineRunNodesOK {
	return &GetPipelineRunNodesOK{}
}

/*
GetPipelineRunNodesOK describes a response with status code 200, with default header values.

ok
*/
type GetPipelineRunNodesOK struct {
	Payload []*models.DevopsPipelineRunNodes
}

// IsSuccess returns true when this get pipeline run nodes o k response has a 2xx status code
func (o *GetPipelineRunNodesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get pipeline run nodes o k response has a 3xx status code
func (o *GetPipelineRunNodesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipeline run nodes o k response has a 4xx status code
func (o *GetPipelineRunNodesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get pipeline run nodes o k response has a 5xx status code
func (o *GetPipelineRunNodesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipeline run nodes o k response a status code equal to that given
func (o *GetPipelineRunNodesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get pipeline run nodes o k response
func (o *GetPipelineRunNodesOK) Code() int {
	return 200
}

func (o *GetPipelineRunNodesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes][%d] getPipelineRunNodesOK %s", 200, payload)
}

func (o *GetPipelineRunNodesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes][%d] getPipelineRunNodesOK %s", 200, payload)
}

func (o *GetPipelineRunNodesOK) GetPayload() []*models.DevopsPipelineRunNodes {
	return o.Payload
}

func (o *GetPipelineRunNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
