// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNodeStepsParams creates a new GetNodeStepsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNodeStepsParams() *GetNodeStepsParams {
	return &GetNodeStepsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodeStepsParamsWithTimeout creates a new GetNodeStepsParams object
// with the ability to set a timeout on a request.
func NewGetNodeStepsParamsWithTimeout(timeout time.Duration) *GetNodeStepsParams {
	return &GetNodeStepsParams{
		timeout: timeout,
	}
}

// NewGetNodeStepsParamsWithContext creates a new GetNodeStepsParams object
// with the ability to set a context for a request.
func NewGetNodeStepsParamsWithContext(ctx context.Context) *GetNodeStepsParams {
	return &GetNodeStepsParams{
		Context: ctx,
	}
}

// NewGetNodeStepsParamsWithHTTPClient creates a new GetNodeStepsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNodeStepsParamsWithHTTPClient(client *http.Client) *GetNodeStepsParams {
	return &GetNodeStepsParams{
		HTTPClient: client,
	}
}

/*
GetNodeStepsParams contains all the parameters to send to the API endpoint

	for the get node steps operation.

	Typically these are written to a http.Request.
*/
type GetNodeStepsParams struct {

	/* Devops.

	   the name of devops project
	*/
	Devops string

	/* Node.

	   pipeline node ID, the stage in pipeline.
	*/
	Node string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run ID, the unique ID for a pipeline once build
	*/
	Run string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get node steps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNodeStepsParams) WithDefaults() *GetNodeStepsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get node steps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNodeStepsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get node steps params
func (o *GetNodeStepsParams) WithTimeout(timeout time.Duration) *GetNodeStepsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get node steps params
func (o *GetNodeStepsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get node steps params
func (o *GetNodeStepsParams) WithContext(ctx context.Context) *GetNodeStepsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get node steps params
func (o *GetNodeStepsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get node steps params
func (o *GetNodeStepsParams) WithHTTPClient(client *http.Client) *GetNodeStepsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get node steps params
func (o *GetNodeStepsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevops adds the devops to the get node steps params
func (o *GetNodeStepsParams) WithDevops(devops string) *GetNodeStepsParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get node steps params
func (o *GetNodeStepsParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithNode adds the node to the get node steps params
func (o *GetNodeStepsParams) WithNode(node string) *GetNodeStepsParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the get node steps params
func (o *GetNodeStepsParams) SetNode(node string) {
	o.Node = node
}

// WithPipeline adds the pipeline to the get node steps params
func (o *GetNodeStepsParams) WithPipeline(pipeline string) *GetNodeStepsParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get node steps params
func (o *GetNodeStepsParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the get node steps params
func (o *GetNodeStepsParams) WithRun(run string) *GetNodeStepsParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the get node steps params
func (o *GetNodeStepsParams) SetRun(run string) {
	o.Run = run
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodeStepsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
