// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBranchStepLogParams creates a new GetBranchStepLogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBranchStepLogParams() *GetBranchStepLogParams {
	return &GetBranchStepLogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBranchStepLogParamsWithTimeout creates a new GetBranchStepLogParams object
// with the ability to set a timeout on a request.
func NewGetBranchStepLogParamsWithTimeout(timeout time.Duration) *GetBranchStepLogParams {
	return &GetBranchStepLogParams{
		timeout: timeout,
	}
}

// NewGetBranchStepLogParamsWithContext creates a new GetBranchStepLogParams object
// with the ability to set a context for a request.
func NewGetBranchStepLogParamsWithContext(ctx context.Context) *GetBranchStepLogParams {
	return &GetBranchStepLogParams{
		Context: ctx,
	}
}

// NewGetBranchStepLogParamsWithHTTPClient creates a new GetBranchStepLogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBranchStepLogParamsWithHTTPClient(client *http.Client) *GetBranchStepLogParams {
	return &GetBranchStepLogParams{
		HTTPClient: client,
	}
}

/*
GetBranchStepLogParams contains all the parameters to send to the API endpoint

	for the get branch step log operation.

	Typically these are written to a http.Request.
*/
type GetBranchStepLogParams struct {

	/* Branch.

	   the name of branch, same as repository branch.
	*/
	Branch string

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Node.

	   pipeline node id, the stage in pipeline.
	*/
	Node string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run id, the unique id for a pipeline once build.
	*/
	Run string

	/* Start.

	   the item number that the search starts from.

	   Format: start=%d
	   Default: "start=0"
	*/
	Start *string

	/* Step.

	   pipeline step id, the step in pipeline.
	*/
	Step string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get branch step log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchStepLogParams) WithDefaults() *GetBranchStepLogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get branch step log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchStepLogParams) SetDefaults() {
	var (
		startDefault = string("start=0")
	)

	val := GetBranchStepLogParams{
		Start: &startDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get branch step log params
func (o *GetBranchStepLogParams) WithTimeout(timeout time.Duration) *GetBranchStepLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get branch step log params
func (o *GetBranchStepLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get branch step log params
func (o *GetBranchStepLogParams) WithContext(ctx context.Context) *GetBranchStepLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get branch step log params
func (o *GetBranchStepLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get branch step log params
func (o *GetBranchStepLogParams) WithHTTPClient(client *http.Client) *GetBranchStepLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get branch step log params
func (o *GetBranchStepLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get branch step log params
func (o *GetBranchStepLogParams) WithBranch(branch string) *GetBranchStepLogParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get branch step log params
func (o *GetBranchStepLogParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDevops adds the devops to the get branch step log params
func (o *GetBranchStepLogParams) WithDevops(devops string) *GetBranchStepLogParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get branch step log params
func (o *GetBranchStepLogParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithNode adds the node to the get branch step log params
func (o *GetBranchStepLogParams) WithNode(node string) *GetBranchStepLogParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the get branch step log params
func (o *GetBranchStepLogParams) SetNode(node string) {
	o.Node = node
}

// WithPipeline adds the pipeline to the get branch step log params
func (o *GetBranchStepLogParams) WithPipeline(pipeline string) *GetBranchStepLogParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get branch step log params
func (o *GetBranchStepLogParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the get branch step log params
func (o *GetBranchStepLogParams) WithRun(run string) *GetBranchStepLogParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the get branch step log params
func (o *GetBranchStepLogParams) SetRun(run string) {
	o.Run = run
}

// WithStart adds the start to the get branch step log params
func (o *GetBranchStepLogParams) WithStart(start *string) *GetBranchStepLogParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get branch step log params
func (o *GetBranchStepLogParams) SetStart(start *string) {
	o.Start = start
}

// WithStep adds the step to the get branch step log params
func (o *GetBranchStepLogParams) WithStep(step string) *GetBranchStepLogParams {
	o.SetStep(step)
	return o
}

// SetStep adds the step to the get branch step log params
func (o *GetBranchStepLogParams) SetStep(step string) {
	o.Step = step
}

// WriteToRequest writes these params to a swagger request
func (o *GetBranchStepLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	if o.Start != nil {

		// query param start
		var qrStart string

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	// path param step
	if err := r.SetPathParam("step", o.Step); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
