// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// GetPipelineBranchReader is a Reader for the GetPipelineBranch structure.
type GetPipelineBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineBranchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches] GetPipelineBranch", response, response.Code())
	}
}

// NewGetPipelineBranchOK creates a GetPipelineBranchOK with default headers values
func NewGetPipelineBranchOK() *GetPipelineBranchOK {
	return &GetPipelineBranchOK{}
}

/*
GetPipelineBranchOK describes a response with status code 200, with default header values.

ok
*/
type GetPipelineBranchOK struct {
	Payload []models.DevopsPipelineBranch
}

// IsSuccess returns true when this get pipeline branch o k response has a 2xx status code
func (o *GetPipelineBranchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get pipeline branch o k response has a 3xx status code
func (o *GetPipelineBranchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipeline branch o k response has a 4xx status code
func (o *GetPipelineBranchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get pipeline branch o k response has a 5xx status code
func (o *GetPipelineBranchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipeline branch o k response a status code equal to that given
func (o *GetPipelineBranchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get pipeline branch o k response
func (o *GetPipelineBranchOK) Code() int {
	return 200
}

func (o *GetPipelineBranchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches][%d] getPipelineBranchOK %s", 200, payload)
}

func (o *GetPipelineBranchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches][%d] getPipelineBranchOK %s", 200, payload)
}

func (o *GetPipelineBranchOK) GetPayload() []models.DevopsPipelineBranch {
	return o.Payload
}

func (o *GetPipelineBranchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
