// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPipelineRunParams creates a new GetPipelineRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPipelineRunParams() *GetPipelineRunParams {
	return &GetPipelineRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPipelineRunParamsWithTimeout creates a new GetPipelineRunParams object
// with the ability to set a timeout on a request.
func NewGetPipelineRunParamsWithTimeout(timeout time.Duration) *GetPipelineRunParams {
	return &GetPipelineRunParams{
		timeout: timeout,
	}
}

// NewGetPipelineRunParamsWithContext creates a new GetPipelineRunParams object
// with the ability to set a context for a request.
func NewGetPipelineRunParamsWithContext(ctx context.Context) *GetPipelineRunParams {
	return &GetPipelineRunParams{
		Context: ctx,
	}
}

// NewGetPipelineRunParamsWithHTTPClient creates a new GetPipelineRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPipelineRunParamsWithHTTPClient(client *http.Client) *GetPipelineRunParams {
	return &GetPipelineRunParams{
		HTTPClient: client,
	}
}

/*
GetPipelineRunParams contains all the parameters to send to the API endpoint

	for the get pipeline run operation.

	Typically these are written to a http.Request.
*/
type GetPipelineRunParams struct {

	/* Namespace.

	   Namespace of the PipelineRun
	*/
	Namespace string

	/* Pipelinerun.

	   Name of the PipelineRun
	*/
	Pipelinerun string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pipeline run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPipelineRunParams) WithDefaults() *GetPipelineRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pipeline run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPipelineRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pipeline run params
func (o *GetPipelineRunParams) WithTimeout(timeout time.Duration) *GetPipelineRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pipeline run params
func (o *GetPipelineRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pipeline run params
func (o *GetPipelineRunParams) WithContext(ctx context.Context) *GetPipelineRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pipeline run params
func (o *GetPipelineRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pipeline run params
func (o *GetPipelineRunParams) WithHTTPClient(client *http.Client) *GetPipelineRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pipeline run params
func (o *GetPipelineRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the get pipeline run params
func (o *GetPipelineRunParams) WithNamespace(namespace string) *GetPipelineRunParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get pipeline run params
func (o *GetPipelineRunParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPipelinerun adds the pipelinerun to the get pipeline run params
func (o *GetPipelineRunParams) WithPipelinerun(pipelinerun string) *GetPipelineRunParams {
	o.SetPipelinerun(pipelinerun)
	return o
}

// SetPipelinerun adds the pipelinerun to the get pipeline run params
func (o *GetPipelineRunParams) SetPipelinerun(pipelinerun string) {
	o.Pipelinerun = pipelinerun
}

// WriteToRequest writes these params to a swagger request
func (o *GetPipelineRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param pipelinerun
	if err := r.SetPathParam("pipelinerun", o.Pipelinerun); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
