// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBranchPipelineParams creates a new GetBranchPipelineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBranchPipelineParams() *GetBranchPipelineParams {
	return &GetBranchPipelineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBranchPipelineParamsWithTimeout creates a new GetBranchPipelineParams object
// with the ability to set a timeout on a request.
func NewGetBranchPipelineParamsWithTimeout(timeout time.Duration) *GetBranchPipelineParams {
	return &GetBranchPipelineParams{
		timeout: timeout,
	}
}

// NewGetBranchPipelineParamsWithContext creates a new GetBranchPipelineParams object
// with the ability to set a context for a request.
func NewGetBranchPipelineParamsWithContext(ctx context.Context) *GetBranchPipelineParams {
	return &GetBranchPipelineParams{
		Context: ctx,
	}
}

// NewGetBranchPipelineParamsWithHTTPClient creates a new GetBranchPipelineParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBranchPipelineParamsWithHTTPClient(client *http.Client) *GetBranchPipelineParams {
	return &GetBranchPipelineParams{
		HTTPClient: client,
	}
}

/*
GetBranchPipelineParams contains all the parameters to send to the API endpoint

	for the get branch pipeline operation.

	Typically these are written to a http.Request.
*/
type GetBranchPipelineParams struct {

	/* Branch.

	   the name of branch, same as repository branch
	*/
	Branch string

	/* Devops.

	   the name of devops project
	*/
	Devops string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get branch pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchPipelineParams) WithDefaults() *GetBranchPipelineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get branch pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchPipelineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get branch pipeline params
func (o *GetBranchPipelineParams) WithTimeout(timeout time.Duration) *GetBranchPipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get branch pipeline params
func (o *GetBranchPipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get branch pipeline params
func (o *GetBranchPipelineParams) WithContext(ctx context.Context) *GetBranchPipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get branch pipeline params
func (o *GetBranchPipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get branch pipeline params
func (o *GetBranchPipelineParams) WithHTTPClient(client *http.Client) *GetBranchPipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get branch pipeline params
func (o *GetBranchPipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get branch pipeline params
func (o *GetBranchPipelineParams) WithBranch(branch string) *GetBranchPipelineParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get branch pipeline params
func (o *GetBranchPipelineParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDevops adds the devops to the get branch pipeline params
func (o *GetBranchPipelineParams) WithDevops(devops string) *GetBranchPipelineParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get branch pipeline params
func (o *GetBranchPipelineParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithPipeline adds the pipeline to the get branch pipeline params
func (o *GetBranchPipelineParams) WithPipeline(pipeline string) *GetBranchPipelineParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get branch pipeline params
func (o *GetBranchPipelineParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WriteToRequest writes these params to a swagger request
func (o *GetBranchPipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
