// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBranchNodeStepsParams creates a new GetBranchNodeStepsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBranchNodeStepsParams() *GetBranchNodeStepsParams {
	return &GetBranchNodeStepsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBranchNodeStepsParamsWithTimeout creates a new GetBranchNodeStepsParams object
// with the ability to set a timeout on a request.
func NewGetBranchNodeStepsParamsWithTimeout(timeout time.Duration) *GetBranchNodeStepsParams {
	return &GetBranchNodeStepsParams{
		timeout: timeout,
	}
}

// NewGetBranchNodeStepsParamsWithContext creates a new GetBranchNodeStepsParams object
// with the ability to set a context for a request.
func NewGetBranchNodeStepsParamsWithContext(ctx context.Context) *GetBranchNodeStepsParams {
	return &GetBranchNodeStepsParams{
		Context: ctx,
	}
}

// NewGetBranchNodeStepsParamsWithHTTPClient creates a new GetBranchNodeStepsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBranchNodeStepsParamsWithHTTPClient(client *http.Client) *GetBranchNodeStepsParams {
	return &GetBranchNodeStepsParams{
		HTTPClient: client,
	}
}

/*
GetBranchNodeStepsParams contains all the parameters to send to the API endpoint

	for the get branch node steps operation.

	Typically these are written to a http.Request.
*/
type GetBranchNodeStepsParams struct {

	/* Branch.

	   the name of branch, same as repository branch.
	*/
	Branch string

	/* Devops.

	   the name of devops project
	*/
	Devops string

	/* Node.

	   pipeline node ID, the stage in pipeline.
	*/
	Node string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run ID, the unique ID for a pipeline once build.
	*/
	Run string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get branch node steps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchNodeStepsParams) WithDefaults() *GetBranchNodeStepsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get branch node steps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchNodeStepsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithTimeout(timeout time.Duration) *GetBranchNodeStepsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithContext(ctx context.Context) *GetBranchNodeStepsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithHTTPClient(client *http.Client) *GetBranchNodeStepsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithBranch(branch string) *GetBranchNodeStepsParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDevops adds the devops to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithDevops(devops string) *GetBranchNodeStepsParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithNode adds the node to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithNode(node string) *GetBranchNodeStepsParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetNode(node string) {
	o.Node = node
}

// WithPipeline adds the pipeline to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithPipeline(pipeline string) *GetBranchNodeStepsParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the get branch node steps params
func (o *GetBranchNodeStepsParams) WithRun(run string) *GetBranchNodeStepsParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the get branch node steps params
func (o *GetBranchNodeStepsParams) SetRun(run string) {
	o.Run = run
}

// WriteToRequest writes these params to a swagger request
func (o *GetBranchNodeStepsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
