// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// GetBranchArtifactsReader is a Reader for the GetBranchArtifacts structure.
type GetBranchArtifactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBranchArtifactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBranchArtifactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/artifacts] GetBranchArtifacts", response, response.Code())
	}
}

// NewGetBranchArtifactsOK creates a GetBranchArtifactsOK with default headers values
func NewGetBranchArtifactsOK() *GetBranchArtifactsOK {
	return &GetBranchArtifactsOK{}
}

/*
GetBranchArtifactsOK describes a response with status code 200, with default header values.

The filed of "Url" in response can download artifacts
*/
type GetBranchArtifactsOK struct {
	Payload []*models.DevopsArtifacts
}

// IsSuccess returns true when this get branch artifacts o k response has a 2xx status code
func (o *GetBranchArtifactsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get branch artifacts o k response has a 3xx status code
func (o *GetBranchArtifactsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get branch artifacts o k response has a 4xx status code
func (o *GetBranchArtifactsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get branch artifacts o k response has a 5xx status code
func (o *GetBranchArtifactsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get branch artifacts o k response a status code equal to that given
func (o *GetBranchArtifactsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get branch artifacts o k response
func (o *GetBranchArtifactsOK) Code() int {
	return 200
}

func (o *GetBranchArtifactsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/artifacts][%d] getBranchArtifactsOK %s", 200, payload)
}

func (o *GetBranchArtifactsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/artifacts][%d] getBranchArtifactsOK %s", 200, payload)
}

func (o *GetBranchArtifactsOK) GetPayload() []*models.DevopsArtifacts {
	return o.Payload
}

func (o *GetBranchArtifactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
