// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConsoleLogParams creates a new GetConsoleLogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConsoleLogParams() *GetConsoleLogParams {
	return &GetConsoleLogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConsoleLogParamsWithTimeout creates a new GetConsoleLogParams object
// with the ability to set a timeout on a request.
func NewGetConsoleLogParamsWithTimeout(timeout time.Duration) *GetConsoleLogParams {
	return &GetConsoleLogParams{
		timeout: timeout,
	}
}

// NewGetConsoleLogParamsWithContext creates a new GetConsoleLogParams object
// with the ability to set a context for a request.
func NewGetConsoleLogParamsWithContext(ctx context.Context) *GetConsoleLogParams {
	return &GetConsoleLogParams{
		Context: ctx,
	}
}

// NewGetConsoleLogParamsWithHTTPClient creates a new GetConsoleLogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConsoleLogParamsWithHTTPClient(client *http.Client) *GetConsoleLogParams {
	return &GetConsoleLogParams{
		HTTPClient: client,
	}
}

/*
GetConsoleLogParams contains all the parameters to send to the API endpoint

	for the get console log operation.

	Typically these are written to a http.Request.
*/
type GetConsoleLogParams struct {

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get console log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConsoleLogParams) WithDefaults() *GetConsoleLogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get console log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConsoleLogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get console log params
func (o *GetConsoleLogParams) WithTimeout(timeout time.Duration) *GetConsoleLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get console log params
func (o *GetConsoleLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get console log params
func (o *GetConsoleLogParams) WithContext(ctx context.Context) *GetConsoleLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get console log params
func (o *GetConsoleLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get console log params
func (o *GetConsoleLogParams) WithHTTPClient(client *http.Client) *GetConsoleLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get console log params
func (o *GetConsoleLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevops adds the devops to the get console log params
func (o *GetConsoleLogParams) WithDevops(devops string) *GetConsoleLogParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get console log params
func (o *GetConsoleLogParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithPipeline adds the pipeline to the get console log params
func (o *GetConsoleLogParams) WithPipeline(pipeline string) *GetConsoleLogParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get console log params
func (o *GetConsoleLogParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WriteToRequest writes these params to a swagger request
func (o *GetConsoleLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
