// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// GetBranchNodeStepsReader is a Reader for the GetBranchNodeSteps structure.
type GetBranchNodeStepsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBranchNodeStepsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBranchNodeStepsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/nodes/{node}/steps] GetBranchNodeSteps", response, response.Code())
	}
}

// NewGetBranchNodeStepsOK creates a GetBranchNodeStepsOK with default headers values
func NewGetBranchNodeStepsOK() *GetBranchNodeStepsOK {
	return &GetBranchNodeStepsOK{}
}

/*
GetBranchNodeStepsOK describes a response with status code 200, with default header values.

ok
*/
type GetBranchNodeStepsOK struct {
	Payload []*models.DevopsNodeSteps
}

// IsSuccess returns true when this get branch node steps o k response has a 2xx status code
func (o *GetBranchNodeStepsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get branch node steps o k response has a 3xx status code
func (o *GetBranchNodeStepsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get branch node steps o k response has a 4xx status code
func (o *GetBranchNodeStepsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get branch node steps o k response has a 5xx status code
func (o *GetBranchNodeStepsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get branch node steps o k response a status code equal to that given
func (o *GetBranchNodeStepsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get branch node steps o k response
func (o *GetBranchNodeStepsOK) Code() int {
	return 200
}

func (o *GetBranchNodeStepsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/nodes/{node}/steps][%d] getBranchNodeStepsOK %s", 200, payload)
}

func (o *GetBranchNodeStepsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/branches/{branch}/runs/{run}/nodes/{node}/steps][%d] getBranchNodeStepsOK %s", 200, payload)
}

func (o *GetBranchNodeStepsOK) GetPayload() []*models.DevopsNodeSteps {
	return o.Payload
}

func (o *GetBranchNodeStepsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
