// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBranchArtifactsParams creates a new GetBranchArtifactsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBranchArtifactsParams() *GetBranchArtifactsParams {
	return &GetBranchArtifactsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBranchArtifactsParamsWithTimeout creates a new GetBranchArtifactsParams object
// with the ability to set a timeout on a request.
func NewGetBranchArtifactsParamsWithTimeout(timeout time.Duration) *GetBranchArtifactsParams {
	return &GetBranchArtifactsParams{
		timeout: timeout,
	}
}

// NewGetBranchArtifactsParamsWithContext creates a new GetBranchArtifactsParams object
// with the ability to set a context for a request.
func NewGetBranchArtifactsParamsWithContext(ctx context.Context) *GetBranchArtifactsParams {
	return &GetBranchArtifactsParams{
		Context: ctx,
	}
}

// NewGetBranchArtifactsParamsWithHTTPClient creates a new GetBranchArtifactsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBranchArtifactsParamsWithHTTPClient(client *http.Client) *GetBranchArtifactsParams {
	return &GetBranchArtifactsParams{
		HTTPClient: client,
	}
}

/*
GetBranchArtifactsParams contains all the parameters to send to the API endpoint

	for the get branch artifacts operation.

	Typically these are written to a http.Request.
*/
type GetBranchArtifactsParams struct {

	/* Branch.

	   the name of branch, same as repository branch.
	*/
	Branch string

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Limit.

	   the limit item count of the search.

	   Format: limit=%d
	*/
	Limit *string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run ID, the unique ID for a pipeline once build.
	*/
	Run string

	/* Start.

	   the item number that the search starts from.

	   Format: start=%d
	*/
	Start *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get branch artifacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchArtifactsParams) WithDefaults() *GetBranchArtifactsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get branch artifacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBranchArtifactsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithTimeout(timeout time.Duration) *GetBranchArtifactsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithContext(ctx context.Context) *GetBranchArtifactsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithHTTPClient(client *http.Client) *GetBranchArtifactsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithBranch(branch string) *GetBranchArtifactsParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDevops adds the devops to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithDevops(devops string) *GetBranchArtifactsParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithLimit adds the limit to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithLimit(limit *string) *GetBranchArtifactsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithPipeline adds the pipeline to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithPipeline(pipeline string) *GetBranchArtifactsParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithRun(run string) *GetBranchArtifactsParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetRun(run string) {
	o.Run = run
}

// WithStart adds the start to the get branch artifacts params
func (o *GetBranchArtifactsParams) WithStart(start *string) *GetBranchArtifactsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get branch artifacts params
func (o *GetBranchArtifactsParams) SetStart(start *string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetBranchArtifactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	if o.Start != nil {

		// query param start
		var qrStart string

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
