// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPipelineRunsV1alpha2Params creates a new ListPipelineRunsV1alpha2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPipelineRunsV1alpha2Params() *ListPipelineRunsV1alpha2Params {
	return &ListPipelineRunsV1alpha2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPipelineRunsV1alpha2ParamsWithTimeout creates a new ListPipelineRunsV1alpha2Params object
// with the ability to set a timeout on a request.
func NewListPipelineRunsV1alpha2ParamsWithTimeout(timeout time.Duration) *ListPipelineRunsV1alpha2Params {
	return &ListPipelineRunsV1alpha2Params{
		timeout: timeout,
	}
}

// NewListPipelineRunsV1alpha2ParamsWithContext creates a new ListPipelineRunsV1alpha2Params object
// with the ability to set a context for a request.
func NewListPipelineRunsV1alpha2ParamsWithContext(ctx context.Context) *ListPipelineRunsV1alpha2Params {
	return &ListPipelineRunsV1alpha2Params{
		Context: ctx,
	}
}

// NewListPipelineRunsV1alpha2ParamsWithHTTPClient creates a new ListPipelineRunsV1alpha2Params object
// with the ability to set a custom HTTPClient for a request.
func NewListPipelineRunsV1alpha2ParamsWithHTTPClient(client *http.Client) *ListPipelineRunsV1alpha2Params {
	return &ListPipelineRunsV1alpha2Params{
		HTTPClient: client,
	}
}

/*
ListPipelineRunsV1alpha2Params contains all the parameters to send to the API endpoint

	for the list pipeline runs v1alpha2 operation.

	Typically these are written to a http.Request.
*/
type ListPipelineRunsV1alpha2Params struct {

	/* Branch.

	   the name of branch, same as repository branch, will be filtered by branch.

	   Format: branch=%s
	*/
	Branch *string

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Limit.

	   the limit item count of the search

	   Format: limit=%d
	*/
	Limit *string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Start.

	   the item number that the search starts from

	   Format: start=%d
	*/
	Start *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list pipeline runs v1alpha2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPipelineRunsV1alpha2Params) WithDefaults() *ListPipelineRunsV1alpha2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list pipeline runs v1alpha2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPipelineRunsV1alpha2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithTimeout(timeout time.Duration) *ListPipelineRunsV1alpha2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithContext(ctx context.Context) *ListPipelineRunsV1alpha2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithHTTPClient(client *http.Client) *ListPipelineRunsV1alpha2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithBranch(branch *string) *ListPipelineRunsV1alpha2Params {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetBranch(branch *string) {
	o.Branch = branch
}

// WithDevops adds the devops to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithDevops(devops string) *ListPipelineRunsV1alpha2Params {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetDevops(devops string) {
	o.Devops = devops
}

// WithLimit adds the limit to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithLimit(limit *string) *ListPipelineRunsV1alpha2Params {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetLimit(limit *string) {
	o.Limit = limit
}

// WithPipeline adds the pipeline to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithPipeline(pipeline string) *ListPipelineRunsV1alpha2Params {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithStart adds the start to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) WithStart(start *string) *ListPipelineRunsV1alpha2Params {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the list pipeline runs v1alpha2 params
func (o *ListPipelineRunsV1alpha2Params) SetStart(start *string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *ListPipelineRunsV1alpha2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Branch != nil {

		// query param branch
		var qrBranch string

		if o.Branch != nil {
			qrBranch = *o.Branch
		}
		qBranch := qrBranch
		if qBranch != "" {

			if err := r.SetQueryParam("branch", qBranch); err != nil {
				return err
			}
		}
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	if o.Start != nil {

		// query param start
		var qrStart string

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
