// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// ReplayPipelineReader is a Reader for the ReplayPipeline structure.
type ReplayPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplayPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplayPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/replay] ReplayPipeline", response, response.Code())
	}
}

// NewReplayPipelineOK creates a ReplayPipelineOK with default headers values
func NewReplayPipelineOK() *ReplayPipelineOK {
	return &ReplayPipelineOK{}
}

/*
ReplayPipelineOK describes a response with status code 200, with default header values.

ok
*/
type ReplayPipelineOK struct {
	Payload *models.DevopsReplayPipeline
}

// IsSuccess returns true when this replay pipeline o k response has a 2xx status code
func (o *ReplayPipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this replay pipeline o k response has a 3xx status code
func (o *ReplayPipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replay pipeline o k response has a 4xx status code
func (o *ReplayPipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this replay pipeline o k response has a 5xx status code
func (o *ReplayPipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this replay pipeline o k response a status code equal to that given
func (o *ReplayPipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the replay pipeline o k response
func (o *ReplayPipelineOK) Code() int {
	return 200
}

func (o *ReplayPipelineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/replay][%d] replayPipelineOK %s", 200, payload)
}

func (o *ReplayPipelineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/replay][%d] replayPipelineOK %s", 200, payload)
}

func (o *ReplayPipelineOK) GetPayload() *models.DevopsReplayPipeline {
	return o.Payload
}

func (o *ReplayPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DevopsReplayPipeline)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
