// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SubmitInputStepReader is a Reader for the SubmitInputStep structure.
type SubmitInputStepReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubmitInputStepReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubmitInputStepOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes/{node}/steps/{step}] SubmitInputStep", response, response.Code())
	}
}

// NewSubmitInputStepOK creates a SubmitInputStepOK with default headers values
func NewSubmitInputStepOK() *SubmitInputStepOK {
	return &SubmitInputStepOK{}
}

/*
SubmitInputStepOK describes a response with status code 200, with default header values.

OK
*/
type SubmitInputStepOK struct {
}

// IsSuccess returns true when this submit input step o k response has a 2xx status code
func (o *SubmitInputStepOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this submit input step o k response has a 3xx status code
func (o *SubmitInputStepOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit input step o k response has a 4xx status code
func (o *SubmitInputStepOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this submit input step o k response has a 5xx status code
func (o *SubmitInputStepOK) IsServerError() bool {
	return false
}

// IsCode returns true when this submit input step o k response a status code equal to that given
func (o *SubmitInputStepOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the submit input step o k response
func (o *SubmitInputStepOK) Code() int {
	return 200
}

func (o *SubmitInputStepOK) Error() string {
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes/{node}/steps/{step}][%d] submitInputStepOK", 200)
}

func (o *SubmitInputStepOK) String() string {
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/pipelines/{pipeline}/runs/{run}/nodes/{node}/steps/{step}][%d] submitInputStepOK", 200)
}

func (o *SubmitInputStepOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
