// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// NewSubmitInputStepParams creates a new SubmitInputStepParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubmitInputStepParams() *SubmitInputStepParams {
	return &SubmitInputStepParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubmitInputStepParamsWithTimeout creates a new SubmitInputStepParams object
// with the ability to set a timeout on a request.
func NewSubmitInputStepParamsWithTimeout(timeout time.Duration) *SubmitInputStepParams {
	return &SubmitInputStepParams{
		timeout: timeout,
	}
}

// NewSubmitInputStepParamsWithContext creates a new SubmitInputStepParams object
// with the ability to set a context for a request.
func NewSubmitInputStepParamsWithContext(ctx context.Context) *SubmitInputStepParams {
	return &SubmitInputStepParams{
		Context: ctx,
	}
}

// NewSubmitInputStepParamsWithHTTPClient creates a new SubmitInputStepParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubmitInputStepParamsWithHTTPClient(client *http.Client) *SubmitInputStepParams {
	return &SubmitInputStepParams{
		HTTPClient: client,
	}
}

/*
SubmitInputStepParams contains all the parameters to send to the API endpoint

	for the submit input step operation.

	Typically these are written to a http.Request.
*/
type SubmitInputStepParams struct {

	// Body.
	Body *models.DevopsCheckPlayload

	/* Devops.

	   DevOps project's ID, e.g. project-RRRRAzLBlLEm
	*/
	Devops string

	/* Node.

	   pipeline node ID, the stage in pipeline.
	*/
	Node string

	/* Pipeline.

	   the name of the CI/CD pipeline
	*/
	Pipeline string

	/* Run.

	   pipeline run ID, the unique ID for a pipeline once build.
	*/
	Run string

	/* Step.

	   pipeline step ID
	*/
	Step string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the submit input step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitInputStepParams) WithDefaults() *SubmitInputStepParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the submit input step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitInputStepParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the submit input step params
func (o *SubmitInputStepParams) WithTimeout(timeout time.Duration) *SubmitInputStepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the submit input step params
func (o *SubmitInputStepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the submit input step params
func (o *SubmitInputStepParams) WithContext(ctx context.Context) *SubmitInputStepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the submit input step params
func (o *SubmitInputStepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the submit input step params
func (o *SubmitInputStepParams) WithHTTPClient(client *http.Client) *SubmitInputStepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the submit input step params
func (o *SubmitInputStepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the submit input step params
func (o *SubmitInputStepParams) WithBody(body *models.DevopsCheckPlayload) *SubmitInputStepParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the submit input step params
func (o *SubmitInputStepParams) SetBody(body *models.DevopsCheckPlayload) {
	o.Body = body
}

// WithDevops adds the devops to the submit input step params
func (o *SubmitInputStepParams) WithDevops(devops string) *SubmitInputStepParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the submit input step params
func (o *SubmitInputStepParams) SetDevops(devops string) {
	o.Devops = devops
}

// WithNode adds the node to the submit input step params
func (o *SubmitInputStepParams) WithNode(node string) *SubmitInputStepParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the submit input step params
func (o *SubmitInputStepParams) SetNode(node string) {
	o.Node = node
}

// WithPipeline adds the pipeline to the submit input step params
func (o *SubmitInputStepParams) WithPipeline(pipeline string) *SubmitInputStepParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the submit input step params
func (o *SubmitInputStepParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithRun adds the run to the submit input step params
func (o *SubmitInputStepParams) WithRun(run string) *SubmitInputStepParams {
	o.SetRun(run)
	return o
}

// SetRun adds the run to the submit input step params
func (o *SubmitInputStepParams) SetRun(run string) {
	o.Run = run
}

// WithStep adds the step to the submit input step params
func (o *SubmitInputStepParams) WithStep(step string) *SubmitInputStepParams {
	o.SetStep(step)
	return o
}

// SetStep adds the step to the submit input step params
func (o *SubmitInputStepParams) SetStep(step string) {
	o.Step = step
}

// WriteToRequest writes these params to a swagger request
func (o *SubmitInputStepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param run
	if err := r.SetPathParam("run", o.Run); err != nil {
		return err
	}

	// path param step
	if err := r.SetPathParam("step", o.Step); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
