// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCredentialParams creates a new DeleteCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCredentialParams() *DeleteCredentialParams {
	return &DeleteCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCredentialParamsWithTimeout creates a new DeleteCredentialParams object
// with the ability to set a timeout on a request.
func NewDeleteCredentialParamsWithTimeout(timeout time.Duration) *DeleteCredentialParams {
	return &DeleteCredentialParams{
		timeout: timeout,
	}
}

// NewDeleteCredentialParamsWithContext creates a new DeleteCredentialParams object
// with the ability to set a context for a request.
func NewDeleteCredentialParamsWithContext(ctx context.Context) *DeleteCredentialParams {
	return &DeleteCredentialParams{
		Context: ctx,
	}
}

// NewDeleteCredentialParamsWithHTTPClient creates a new DeleteCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCredentialParamsWithHTTPClient(client *http.Client) *DeleteCredentialParams {
	return &DeleteCredentialParams{
		HTTPClient: client,
	}
}

/*
DeleteCredentialParams contains all the parameters to send to the API endpoint

	for the delete credential operation.

	Typically these are written to a http.Request.
*/
type DeleteCredentialParams struct {

	/* Credential.

	   credential name
	*/
	Credential string

	/* Devops.

	   project name
	*/
	Devops string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCredentialParams) WithDefaults() *DeleteCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete credential params
func (o *DeleteCredentialParams) WithTimeout(timeout time.Duration) *DeleteCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete credential params
func (o *DeleteCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete credential params
func (o *DeleteCredentialParams) WithContext(ctx context.Context) *DeleteCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete credential params
func (o *DeleteCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete credential params
func (o *DeleteCredentialParams) WithHTTPClient(client *http.Client) *DeleteCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete credential params
func (o *DeleteCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredential adds the credential to the delete credential params
func (o *DeleteCredentialParams) WithCredential(credential string) *DeleteCredentialParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the delete credential params
func (o *DeleteCredentialParams) SetCredential(credential string) {
	o.Credential = credential
}

// WithDevops adds the devops to the delete credential params
func (o *DeleteCredentialParams) WithDevops(devops string) *DeleteCredentialParams {
	o.SetDevops(devops)
	return o
}

// SetDevops adds the devops to the delete credential params
func (o *DeleteCredentialParams) SetDevops(devops string) {
	o.Devops = devops
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param credential
	if err := r.SetPathParam("credential", o.Credential); err != nil {
		return err
	}

	// path param devops
	if err := r.SetPathParam("devops", o.Devops); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
