// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// GetProjectCredentialUsageReader is a Reader for the GetProjectCredentialUsage structure.
type GetProjectCredentialUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectCredentialUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectCredentialUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/credentials/{credential}/usage] GetProjectCredentialUsage", response, response.Code())
	}
}

// NewGetProjectCredentialUsageOK creates a GetProjectCredentialUsageOK with default headers values
func NewGetProjectCredentialUsageOK() *GetProjectCredentialUsageOK {
	return &GetProjectCredentialUsageOK{}
}

/*
GetProjectCredentialUsageOK describes a response with status code 200, with default header values.

ok
*/
type GetProjectCredentialUsageOK struct {
	Payload *models.DevopsCredential
}

// IsSuccess returns true when this get project credential usage o k response has a 2xx status code
func (o *GetProjectCredentialUsageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project credential usage o k response has a 3xx status code
func (o *GetProjectCredentialUsageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project credential usage o k response has a 4xx status code
func (o *GetProjectCredentialUsageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project credential usage o k response has a 5xx status code
func (o *GetProjectCredentialUsageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project credential usage o k response a status code equal to that given
func (o *GetProjectCredentialUsageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project credential usage o k response
func (o *GetProjectCredentialUsageOK) Code() int {
	return 200
}

func (o *GetProjectCredentialUsageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/credentials/{credential}/usage][%d] getProjectCredentialUsageOK %s", 200, payload)
}

func (o *GetProjectCredentialUsageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/namespaces/{devops}/credentials/{credential}/usage][%d] getProjectCredentialUsageOK %s", 200, payload)
}

func (o *GetProjectCredentialUsageOK) GetPayload() *models.DevopsCredential {
	return o.Payload
}

func (o *GetProjectCredentialUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DevopsCredential)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
