// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// ListCredentialReader is a Reader for the ListCredential structure.
type ListCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/credentials] ListCredential", response, response.Code())
	}
}

// NewListCredentialOK creates a ListCredentialOK with default headers values
func NewListCredentialOK() *ListCredentialOK {
	return &ListCredentialOK{}
}

/*
ListCredentialOK describes a response with status code 200, with default header values.

ok
*/
type ListCredentialOK struct {
	Payload *models.APIListResult
}

// IsSuccess returns true when this list credential o k response has a 2xx status code
func (o *ListCredentialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list credential o k response has a 3xx status code
func (o *ListCredentialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list credential o k response has a 4xx status code
func (o *ListCredentialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list credential o k response has a 5xx status code
func (o *ListCredentialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list credential o k response a status code equal to that given
func (o *ListCredentialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list credential o k response
func (o *ListCredentialOK) Code() int {
	return 200
}

func (o *ListCredentialOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/credentials][%d] listCredentialOK %s", 200, payload)
}

func (o *ListCredentialOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/credentials][%d] listCredentialOK %s", 200, payload)
}

func (o *ListCredentialOK) GetPayload() *models.APIListResult {
	return o.Payload
}

func (o *ListCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
