// Code generated by go-swagger; DO NOT EDIT.

package git_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DownloadFileFromBranchReader is a Reader for the DownloadFileFromBranch structure.
type DownloadFileFromBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DownloadFileFromBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDownloadFileFromBranchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/branches/{branch}/rawfiles/{file}] DownloadFileFromBranch", response, response.Code())
	}
}

// NewDownloadFileFromBranchOK creates a DownloadFileFromBranchOK with default headers values
func NewDownloadFileFromBranchOK() *DownloadFileFromBranchOK {
	return &DownloadFileFromBranchOK{}
}

/*
DownloadFileFromBranchOK describes a response with status code 200, with default header values.

ok
*/
type DownloadFileFromBranchOK struct {
	Payload []int64
}

// IsSuccess returns true when this download file from branch o k response has a 2xx status code
func (o *DownloadFileFromBranchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this download file from branch o k response has a 3xx status code
func (o *DownloadFileFromBranchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this download file from branch o k response has a 4xx status code
func (o *DownloadFileFromBranchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this download file from branch o k response has a 5xx status code
func (o *DownloadFileFromBranchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this download file from branch o k response a status code equal to that given
func (o *DownloadFileFromBranchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the download file from branch o k response
func (o *DownloadFileFromBranchOK) Code() int {
	return 200
}

func (o *DownloadFileFromBranchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/branches/{branch}/rawfiles/{file}][%d] downloadFileFromBranchOK %s", 200, payload)
}

func (o *DownloadFileFromBranchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/branches/{branch}/rawfiles/{file}][%d] downloadFileFromBranchOK %s", 200, payload)
}

func (o *DownloadFileFromBranchOK) GetPayload() []int64 {
	return o.Payload
}

func (o *DownloadFileFromBranchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
