// Code generated by go-swagger; DO NOT EDIT.

package git_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kubesphere.io/devops-client/models"
)

// GetCommitReader is a Reader for the GetCommit structure.
type GetCommitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCommitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCommitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/commits/{commit}] GetCommit", response, response.Code())
	}
}

// NewGetCommitOK creates a GetCommitOK with default headers values
func NewGetCommitOK() *GetCommitOK {
	return &GetCommitOK{}
}

/*
GetCommitOK describes a response with status code 200, with default header values.

ok
*/
type GetCommitOK struct {
	Payload *models.GitopsCommitInfo
}

// IsSuccess returns true when this get commit o k response has a 2xx status code
func (o *GetCommitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get commit o k response has a 3xx status code
func (o *GetCommitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get commit o k response has a 4xx status code
func (o *GetCommitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get commit o k response has a 5xx status code
func (o *GetCommitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get commit o k response a status code equal to that given
func (o *GetCommitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get commit o k response
func (o *GetCommitOK) Code() int {
	return 200
}

func (o *GetCommitOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/commits/{commit}][%d] getCommitOK %s", 200, payload)
}

func (o *GetCommitOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/namespaces/{namespace}/gitrepositories/{gitrepository}/commits/{commit}][%d] getCommitOK %s", 200, payload)
}

func (o *GetCommitOK) GetPayload() *models.GitopsCommitInfo {
	return o.Payload
}

func (o *GetCommitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitopsCommitInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
