// Code generated by go-swagger; DO NOT EDIT.

package git_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUploadFilesParams creates a new UploadFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadFilesParams() *UploadFilesParams {
	return &UploadFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadFilesParamsWithTimeout creates a new UploadFilesParams object
// with the ability to set a timeout on a request.
func NewUploadFilesParamsWithTimeout(timeout time.Duration) *UploadFilesParams {
	return &UploadFilesParams{
		timeout: timeout,
	}
}

// NewUploadFilesParamsWithContext creates a new UploadFilesParams object
// with the ability to set a context for a request.
func NewUploadFilesParamsWithContext(ctx context.Context) *UploadFilesParams {
	return &UploadFilesParams{
		Context: ctx,
	}
}

// NewUploadFilesParamsWithHTTPClient creates a new UploadFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadFilesParamsWithHTTPClient(client *http.Client) *UploadFilesParams {
	return &UploadFilesParams{
		HTTPClient: client,
	}
}

/*
UploadFilesParams contains all the parameters to send to the API endpoint

	for the upload files operation.

	Typically these are written to a http.Request.
*/
type UploadFilesParams struct {

	/* FileX.

	   the file of fileX, X starts from 0
	*/
	FileX runtime.NamedReadCloser

	/* FileXName.

	   the target path in repository, X starts from 0
	*/
	FileXName *string

	/* Gitrepository.

	   The GitRepository customs resource
	*/
	Gitrepository string

	/* Namespace.

	   The namespace name
	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadFilesParams) WithDefaults() *UploadFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload files params
func (o *UploadFilesParams) WithTimeout(timeout time.Duration) *UploadFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload files params
func (o *UploadFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload files params
func (o *UploadFilesParams) WithContext(ctx context.Context) *UploadFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload files params
func (o *UploadFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload files params
func (o *UploadFilesParams) WithHTTPClient(client *http.Client) *UploadFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload files params
func (o *UploadFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileX adds the fileX to the upload files params
func (o *UploadFilesParams) WithFileX(fileX runtime.NamedReadCloser) *UploadFilesParams {
	o.SetFileX(fileX)
	return o
}

// SetFileX adds the fileX to the upload files params
func (o *UploadFilesParams) SetFileX(fileX runtime.NamedReadCloser) {
	o.FileX = fileX
}

// WithFileXName adds the fileXName to the upload files params
func (o *UploadFilesParams) WithFileXName(fileXName *string) *UploadFilesParams {
	o.SetFileXName(fileXName)
	return o
}

// SetFileXName adds the fileXName to the upload files params
func (o *UploadFilesParams) SetFileXName(fileXName *string) {
	o.FileXName = fileXName
}

// WithGitrepository adds the gitrepository to the upload files params
func (o *UploadFilesParams) WithGitrepository(gitrepository string) *UploadFilesParams {
	o.SetGitrepository(gitrepository)
	return o
}

// SetGitrepository adds the gitrepository to the upload files params
func (o *UploadFilesParams) SetGitrepository(gitrepository string) {
	o.Gitrepository = gitrepository
}

// WithNamespace adds the namespace to the upload files params
func (o *UploadFilesParams) WithNamespace(namespace string) *UploadFilesParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the upload files params
func (o *UploadFilesParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *UploadFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FileX != nil {

		if o.FileX != nil {
			// form file param fileX
			if err := r.SetFileParam("fileX", o.FileX); err != nil {
				return err
			}
		}
	}

	if o.FileXName != nil {

		// form param fileX_name
		var frFileXName string
		if o.FileXName != nil {
			frFileXName = *o.FileXName
		}
		fFileXName := frFileXName
		if fFileXName != "" {
			if err := r.SetFormParam("fileX_name", fFileXName); err != nil {
				return err
			}
		}
	}

	// path param gitrepository
	if err := r.SetPathParam("gitrepository", o.Gitrepository); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
