// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_step_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ClusterStepTemplatesReader is a Reader for the ClusterStepTemplates structure.
type ClusterStepTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClusterStepTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClusterStepTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates] clusterStepTemplates", response, response.Code())
	}
}

// NewClusterStepTemplatesOK creates a ClusterStepTemplatesOK with default headers values
func NewClusterStepTemplatesOK() *ClusterStepTemplatesOK {
	return &ClusterStepTemplatesOK{}
}

/*
ClusterStepTemplatesOK describes a response with status code 200, with default header values.

OK
*/
type ClusterStepTemplatesOK struct {
}

// IsSuccess returns true when this cluster step templates o k response has a 2xx status code
func (o *ClusterStepTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cluster step templates o k response has a 3xx status code
func (o *ClusterStepTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cluster step templates o k response has a 4xx status code
func (o *ClusterStepTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cluster step templates o k response has a 5xx status code
func (o *ClusterStepTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cluster step templates o k response a status code equal to that given
func (o *ClusterStepTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the cluster step templates o k response
func (o *ClusterStepTemplatesOK) Code() int {
	return 200
}

func (o *ClusterStepTemplatesOK) Error() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates][%d] clusterStepTemplatesOK", 200)
}

func (o *ClusterStepTemplatesOK) String() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates][%d] clusterStepTemplatesOK", 200)
}

func (o *ClusterStepTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
