// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_step_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetClusterStepTemplateReader is a Reader for the GetClusterStepTemplate structure.
type GetClusterStepTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterStepTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClusterStepTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates/{clustersteptemplate}] getClusterStepTemplate", response, response.Code())
	}
}

// NewGetClusterStepTemplateOK creates a GetClusterStepTemplateOK with default headers values
func NewGetClusterStepTemplateOK() *GetClusterStepTemplateOK {
	return &GetClusterStepTemplateOK{}
}

/*
GetClusterStepTemplateOK describes a response with status code 200, with default header values.

OK
*/
type GetClusterStepTemplateOK struct {
}

// IsSuccess returns true when this get cluster step template o k response has a 2xx status code
func (o *GetClusterStepTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cluster step template o k response has a 3xx status code
func (o *GetClusterStepTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cluster step template o k response has a 4xx status code
func (o *GetClusterStepTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cluster step template o k response has a 5xx status code
func (o *GetClusterStepTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cluster step template o k response a status code equal to that given
func (o *GetClusterStepTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cluster step template o k response
func (o *GetClusterStepTemplateOK) Code() int {
	return 200
}

func (o *GetClusterStepTemplateOK) Error() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates/{clustersteptemplate}][%d] getClusterStepTemplateOK", 200)
}

func (o *GetClusterStepTemplateOK) String() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates/{clustersteptemplate}][%d] getClusterStepTemplateOK", 200)
}

func (o *GetClusterStepTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
