// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_step_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterStepTemplateParams creates a new GetClusterStepTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterStepTemplateParams() *GetClusterStepTemplateParams {
	return &GetClusterStepTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterStepTemplateParamsWithTimeout creates a new GetClusterStepTemplateParams object
// with the ability to set a timeout on a request.
func NewGetClusterStepTemplateParamsWithTimeout(timeout time.Duration) *GetClusterStepTemplateParams {
	return &GetClusterStepTemplateParams{
		timeout: timeout,
	}
}

// NewGetClusterStepTemplateParamsWithContext creates a new GetClusterStepTemplateParams object
// with the ability to set a context for a request.
func NewGetClusterStepTemplateParamsWithContext(ctx context.Context) *GetClusterStepTemplateParams {
	return &GetClusterStepTemplateParams{
		Context: ctx,
	}
}

// NewGetClusterStepTemplateParamsWithHTTPClient creates a new GetClusterStepTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterStepTemplateParamsWithHTTPClient(client *http.Client) *GetClusterStepTemplateParams {
	return &GetClusterStepTemplateParams{
		HTTPClient: client,
	}
}

/*
GetClusterStepTemplateParams contains all the parameters to send to the API endpoint

	for the get cluster step template operation.

	Typically these are written to a http.Request.
*/
type GetClusterStepTemplateParams struct {

	/* Clustersteptemplate.

	   The name of clustersteptemplate
	*/
	Clustersteptemplate string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster step template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterStepTemplateParams) WithDefaults() *GetClusterStepTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster step template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterStepTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster step template params
func (o *GetClusterStepTemplateParams) WithTimeout(timeout time.Duration) *GetClusterStepTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster step template params
func (o *GetClusterStepTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster step template params
func (o *GetClusterStepTemplateParams) WithContext(ctx context.Context) *GetClusterStepTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster step template params
func (o *GetClusterStepTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster step template params
func (o *GetClusterStepTemplateParams) WithHTTPClient(client *http.Client) *GetClusterStepTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster step template params
func (o *GetClusterStepTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClustersteptemplate adds the clustersteptemplate to the get cluster step template params
func (o *GetClusterStepTemplateParams) WithClustersteptemplate(clustersteptemplate string) *GetClusterStepTemplateParams {
	o.SetClustersteptemplate(clustersteptemplate)
	return o
}

// SetClustersteptemplate adds the clustersteptemplate to the get cluster step template params
func (o *GetClusterStepTemplateParams) SetClustersteptemplate(clustersteptemplate string) {
	o.Clustersteptemplate = clustersteptemplate
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterStepTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clustersteptemplate
	if err := r.SetPathParam("clustersteptemplate", o.Clustersteptemplate); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
