// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new dev ops project API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new dev ops project API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new dev ops project API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for dev ops project API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateDevOpsProject(params *CreateDevOpsProjectParams, opts ...ClientOption) (*CreateDevOpsProjectOK, error)

	DeleteDevOpsProject(params *DeleteDevOpsProjectParams, opts ...ClientOption) (*DeleteDevOpsProjectOK, error)

	GetDevOpsProject(params *GetDevOpsProjectParams, opts ...ClientOption) (*GetDevOpsProjectOK, error)

	ListDevOpsProject(params *ListDevOpsProjectParams, opts ...ClientOption) (*ListDevOpsProjectOK, error)

	ListDevOpsProjectForWorkspaceMember(params *ListDevOpsProjectForWorkspaceMemberParams, opts ...ClientOption) (*ListDevOpsProjectForWorkspaceMemberOK, error)

	UpdateDevOpsProject(params *UpdateDevOpsProjectParams, opts ...ClientOption) (*UpdateDevOpsProjectOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateDevOpsProject creates the devopsproject of the specified workspace for the current user
*/
func (a *Client) CreateDevOpsProject(params *CreateDevOpsProjectParams, opts ...ClientOption) (*CreateDevOpsProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateDevOpsProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateDevOpsProject",
		Method:             "POST",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/namespaces",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateDevOpsProjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateDevOpsProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateDevOpsProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteDevOpsProject gets the devopsproject of the specified workspace for the current user
*/
func (a *Client) DeleteDevOpsProject(params *DeleteDevOpsProjectParams, opts ...ClientOption) (*DeleteDevOpsProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteDevOpsProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteDevOpsProject",
		Method:             "DELETE",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/namespaces/{devops}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteDevOpsProjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteDevOpsProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteDevOpsProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetDevOpsProject gets the devops project of the specified workspace for the current user
*/
func (a *Client) GetDevOpsProject(params *GetDevOpsProjectParams, opts ...ClientOption) (*GetDevOpsProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDevOpsProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetDevOpsProject",
		Method:             "GET",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/namespaces/{devops}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetDevOpsProjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDevOpsProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetDevOpsProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListDevOpsProject lists the devopsproject of the specified workspace for the current user
*/
func (a *Client) ListDevOpsProject(params *ListDevOpsProjectParams, opts ...ClientOption) (*ListDevOpsProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDevOpsProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListDevOpsProject",
		Method:             "GET",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/namespaces",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListDevOpsProjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDevOpsProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListDevOpsProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListDevOpsProjectForWorkspaceMember lists the devopsproject of the specified workspace for the current user
*/
func (a *Client) ListDevOpsProjectForWorkspaceMember(params *ListDevOpsProjectForWorkspaceMemberParams, opts ...ClientOption) (*ListDevOpsProjectForWorkspaceMemberOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDevOpsProjectForWorkspaceMemberParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListDevOpsProjectForWorkspaceMember",
		Method:             "GET",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/workspacemembers/{workspacemember}/namespaces",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListDevOpsProjectForWorkspaceMemberReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDevOpsProjectForWorkspaceMemberOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListDevOpsProjectForWorkspaceMember: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateDevOpsProject puts the devopsproject of the specified workspace for the current user
*/
func (a *Client) UpdateDevOpsProject(params *UpdateDevOpsProjectParams, opts ...ClientOption) (*UpdateDevOpsProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateDevOpsProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateDevOpsProject",
		Method:             "PUT",
		PathPattern:        "/kapis/devops.kubesphere.io/v1alpha3/workspaces/{workspace}/namespaces/{devops}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateDevOpsProjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateDevOpsProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateDevOpsProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
