// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// HandleRenderTemplateReader is a Reader for the HandleRenderTemplate structure.
type HandleRenderTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HandleRenderTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHandleRenderTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/templates/{template}/render] handleRenderTemplate", response, response.Code())
	}
}

// NewHandleRenderTemplateOK creates a HandleRenderTemplateOK with default headers values
func NewHandleRenderTemplateOK() *HandleRenderTemplateOK {
	return &HandleRenderTemplateOK{}
}

/*
HandleRenderTemplateOK describes a response with status code 200, with default header values.

ok
*/
type HandleRenderTemplateOK struct {
	Payload *models.V1alpha3Template
}

// IsSuccess returns true when this handle render template o k response has a 2xx status code
func (o *HandleRenderTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this handle render template o k response has a 3xx status code
func (o *HandleRenderTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this handle render template o k response has a 4xx status code
func (o *HandleRenderTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this handle render template o k response has a 5xx status code
func (o *HandleRenderTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this handle render template o k response a status code equal to that given
func (o *HandleRenderTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the handle render template o k response
func (o *HandleRenderTemplateOK) Code() int {
	return 200
}

func (o *HandleRenderTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/templates/{template}/render][%d] handleRenderTemplateOK %s", 200, payload)
}

func (o *HandleRenderTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha3/namespaces/{devops}/templates/{template}/render][%d] handleRenderTemplateOK %s", 200, payload)
}

func (o *HandleRenderTemplateOK) GetPayload() *models.V1alpha3Template {
	return o.Payload
}

func (o *HandleRenderTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha3Template)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
