// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_cluster_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHandleQueryClusterTemplatesParams creates a new HandleQueryClusterTemplatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHandleQueryClusterTemplatesParams() *HandleQueryClusterTemplatesParams {
	return &HandleQueryClusterTemplatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHandleQueryClusterTemplatesParamsWithTimeout creates a new HandleQueryClusterTemplatesParams object
// with the ability to set a timeout on a request.
func NewHandleQueryClusterTemplatesParamsWithTimeout(timeout time.Duration) *HandleQueryClusterTemplatesParams {
	return &HandleQueryClusterTemplatesParams{
		timeout: timeout,
	}
}

// NewHandleQueryClusterTemplatesParamsWithContext creates a new HandleQueryClusterTemplatesParams object
// with the ability to set a context for a request.
func NewHandleQueryClusterTemplatesParamsWithContext(ctx context.Context) *HandleQueryClusterTemplatesParams {
	return &HandleQueryClusterTemplatesParams{
		Context: ctx,
	}
}

// NewHandleQueryClusterTemplatesParamsWithHTTPClient creates a new HandleQueryClusterTemplatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewHandleQueryClusterTemplatesParamsWithHTTPClient(client *http.Client) *HandleQueryClusterTemplatesParams {
	return &HandleQueryClusterTemplatesParams{
		HTTPClient: client,
	}
}

/*
HandleQueryClusterTemplatesParams contains all the parameters to send to the API endpoint

	for the handle query cluster templates operation.

	Typically these are written to a http.Request.
*/
type HandleQueryClusterTemplatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the handle query cluster templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleQueryClusterTemplatesParams) WithDefaults() *HandleQueryClusterTemplatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the handle query cluster templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleQueryClusterTemplatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) WithTimeout(timeout time.Duration) *HandleQueryClusterTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) WithContext(ctx context.Context) *HandleQueryClusterTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) WithHTTPClient(client *http.Client) *HandleQueryClusterTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the handle query cluster templates params
func (o *HandleQueryClusterTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HandleQueryClusterTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
