// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_cluster_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// HandleQueryClusterTemplatesReader is a Reader for the HandleQueryClusterTemplates structure.
type HandleQueryClusterTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HandleQueryClusterTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHandleQueryClusterTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/clustertemplates] handleQueryClusterTemplates", response, response.Code())
	}
}

// NewHandleQueryClusterTemplatesOK creates a HandleQueryClusterTemplatesOK with default headers values
func NewHandleQueryClusterTemplatesOK() *HandleQueryClusterTemplatesOK {
	return &HandleQueryClusterTemplatesOK{}
}

/*
HandleQueryClusterTemplatesOK describes a response with status code 200, with default header values.

ok
*/
type HandleQueryClusterTemplatesOK struct {
	Payload *models.TemplatePageResult
}

// IsSuccess returns true when this handle query cluster templates o k response has a 2xx status code
func (o *HandleQueryClusterTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this handle query cluster templates o k response has a 3xx status code
func (o *HandleQueryClusterTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this handle query cluster templates o k response has a 4xx status code
func (o *HandleQueryClusterTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this handle query cluster templates o k response has a 5xx status code
func (o *HandleQueryClusterTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this handle query cluster templates o k response a status code equal to that given
func (o *HandleQueryClusterTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the handle query cluster templates o k response
func (o *HandleQueryClusterTemplatesOK) Code() int {
	return 200
}

func (o *HandleQueryClusterTemplatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustertemplates][%d] handleQueryClusterTemplatesOK %s", 200, payload)
}

func (o *HandleQueryClusterTemplatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/clustertemplates][%d] handleQueryClusterTemplatesOK %s", 200, payload)
}

func (o *HandleQueryClusterTemplatesOK) GetPayload() *models.TemplatePageResult {
	return o.Payload
}

func (o *HandleQueryClusterTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TemplatePageResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
