// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_scm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// NewCreateSCMServersParams creates a new CreateSCMServersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSCMServersParams() *CreateSCMServersParams {
	return &CreateSCMServersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSCMServersParamsWithTimeout creates a new CreateSCMServersParams object
// with the ability to set a timeout on a request.
func NewCreateSCMServersParamsWithTimeout(timeout time.Duration) *CreateSCMServersParams {
	return &CreateSCMServersParams{
		timeout: timeout,
	}
}

// NewCreateSCMServersParamsWithContext creates a new CreateSCMServersParams object
// with the ability to set a context for a request.
func NewCreateSCMServersParamsWithContext(ctx context.Context) *CreateSCMServersParams {
	return &CreateSCMServersParams{
		Context: ctx,
	}
}

// NewCreateSCMServersParamsWithHTTPClient creates a new CreateSCMServersParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSCMServersParamsWithHTTPClient(client *http.Client) *CreateSCMServersParams {
	return &CreateSCMServersParams{
		HTTPClient: client,
	}
}

/*
CreateSCMServersParams contains all the parameters to send to the API endpoint

	for the create s c m servers operation.

	Typically these are written to a http.Request.
*/
type CreateSCMServersParams struct {

	// Body.
	Body *models.DevopsCreateScmServerReq

	/* Scm.

	   The ID of the source configuration management (SCM).
	*/
	Scm string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create s c m servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSCMServersParams) WithDefaults() *CreateSCMServersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create s c m servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSCMServersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create s c m servers params
func (o *CreateSCMServersParams) WithTimeout(timeout time.Duration) *CreateSCMServersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create s c m servers params
func (o *CreateSCMServersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create s c m servers params
func (o *CreateSCMServersParams) WithContext(ctx context.Context) *CreateSCMServersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create s c m servers params
func (o *CreateSCMServersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create s c m servers params
func (o *CreateSCMServersParams) WithHTTPClient(client *http.Client) *CreateSCMServersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create s c m servers params
func (o *CreateSCMServersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create s c m servers params
func (o *CreateSCMServersParams) WithBody(body *models.DevopsCreateScmServerReq) *CreateSCMServersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create s c m servers params
func (o *CreateSCMServersParams) SetBody(body *models.DevopsCreateScmServerReq) {
	o.Body = body
}

// WithScm adds the scm to the create s c m servers params
func (o *CreateSCMServersParams) WithScm(scm string) *CreateSCMServersParams {
	o.SetScm(scm)
	return o
}

// SetScm adds the scm to the create s c m servers params
func (o *CreateSCMServersParams) SetScm(scm string) {
	o.Scm = scm
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSCMServersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param scm
	if err := r.SetPathParam("scm", o.Scm); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
