// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_scm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// GetSCMOrgReader is a Reader for the GetSCMOrg structure.
type GetSCMOrgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSCMOrgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSCMOrgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/scms/{scm}/organizations] GetSCMOrg", response, response.Code())
	}
}

// NewGetSCMOrgOK creates a GetSCMOrgOK with default headers values
func NewGetSCMOrgOK() *GetSCMOrgOK {
	return &GetSCMOrgOK{}
}

/*
GetSCMOrgOK describes a response with status code 200, with default header values.

ok
*/
type GetSCMOrgOK struct {
	Payload []*models.DevopsSCMOrg
}

// IsSuccess returns true when this get s c m org o k response has a 2xx status code
func (o *GetSCMOrgOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get s c m org o k response has a 3xx status code
func (o *GetSCMOrgOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get s c m org o k response has a 4xx status code
func (o *GetSCMOrgOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get s c m org o k response has a 5xx status code
func (o *GetSCMOrgOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get s c m org o k response a status code equal to that given
func (o *GetSCMOrgOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get s c m org o k response
func (o *GetSCMOrgOK) Code() int {
	return 200
}

func (o *GetSCMOrgOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/scms/{scm}/organizations][%d] getSCMOrgOK %s", 200, payload)
}

func (o *GetSCMOrgOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/scms/{scm}/organizations][%d] getSCMOrgOK %s", 200, payload)
}

func (o *GetSCMOrgOK) GetPayload() []*models.DevopsSCMOrg {
	return o.Payload
}

func (o *GetSCMOrgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
