// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_scm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSCMServersParams creates a new GetSCMServersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSCMServersParams() *GetSCMServersParams {
	return &GetSCMServersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSCMServersParamsWithTimeout creates a new GetSCMServersParams object
// with the ability to set a timeout on a request.
func NewGetSCMServersParamsWithTimeout(timeout time.Duration) *GetSCMServersParams {
	return &GetSCMServersParams{
		timeout: timeout,
	}
}

// NewGetSCMServersParamsWithContext creates a new GetSCMServersParams object
// with the ability to set a context for a request.
func NewGetSCMServersParamsWithContext(ctx context.Context) *GetSCMServersParams {
	return &GetSCMServersParams{
		Context: ctx,
	}
}

// NewGetSCMServersParamsWithHTTPClient creates a new GetSCMServersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSCMServersParamsWithHTTPClient(client *http.Client) *GetSCMServersParams {
	return &GetSCMServersParams{
		HTTPClient: client,
	}
}

/*
GetSCMServersParams contains all the parameters to send to the API endpoint

	for the get s c m servers operation.

	Typically these are written to a http.Request.
*/
type GetSCMServersParams struct {

	/* Scm.

	   The ID of the source configuration management (SCM).
	*/
	Scm string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get s c m servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSCMServersParams) WithDefaults() *GetSCMServersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get s c m servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSCMServersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get s c m servers params
func (o *GetSCMServersParams) WithTimeout(timeout time.Duration) *GetSCMServersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get s c m servers params
func (o *GetSCMServersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get s c m servers params
func (o *GetSCMServersParams) WithContext(ctx context.Context) *GetSCMServersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get s c m servers params
func (o *GetSCMServersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get s c m servers params
func (o *GetSCMServersParams) WithHTTPClient(client *http.Client) *GetSCMServersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get s c m servers params
func (o *GetSCMServersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithScm adds the scm to the get s c m servers params
func (o *GetSCMServersParams) WithScm(scm string) *GetSCMServersParams {
	o.SetScm(scm)
	return o
}

// SetScm adds the scm to the get s c m servers params
func (o *GetSCMServersParams) SetScm(scm string) {
	o.Scm = scm
}

// WriteToRequest writes these params to a swagger request
func (o *GetSCMServersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param scm
	if err := r.SetPathParam("scm", o.Scm); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
