// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_scm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSCMOrgParams creates a new GetSCMOrgParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSCMOrgParams() *GetSCMOrgParams {
	return &GetSCMOrgParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSCMOrgParamsWithTimeout creates a new GetSCMOrgParams object
// with the ability to set a timeout on a request.
func NewGetSCMOrgParamsWithTimeout(timeout time.Duration) *GetSCMOrgParams {
	return &GetSCMOrgParams{
		timeout: timeout,
	}
}

// NewGetSCMOrgParamsWithContext creates a new GetSCMOrgParams object
// with the ability to set a context for a request.
func NewGetSCMOrgParamsWithContext(ctx context.Context) *GetSCMOrgParams {
	return &GetSCMOrgParams{
		Context: ctx,
	}
}

// NewGetSCMOrgParamsWithHTTPClient creates a new GetSCMOrgParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSCMOrgParamsWithHTTPClient(client *http.Client) *GetSCMOrgParams {
	return &GetSCMOrgParams{
		HTTPClient: client,
	}
}

/*
GetSCMOrgParams contains all the parameters to send to the API endpoint

	for the get s c m org operation.

	Typically these are written to a http.Request.
*/
type GetSCMOrgParams struct {

	/* CredentialID.

	   credential ID for source configuration management (SCM).

	   Format: credentialId=%s
	*/
	CredentialID string

	/* Scm.

	   the ID of the source configuration management (SCM).
	*/
	Scm string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get s c m org params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSCMOrgParams) WithDefaults() *GetSCMOrgParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get s c m org params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSCMOrgParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get s c m org params
func (o *GetSCMOrgParams) WithTimeout(timeout time.Duration) *GetSCMOrgParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get s c m org params
func (o *GetSCMOrgParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get s c m org params
func (o *GetSCMOrgParams) WithContext(ctx context.Context) *GetSCMOrgParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get s c m org params
func (o *GetSCMOrgParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get s c m org params
func (o *GetSCMOrgParams) WithHTTPClient(client *http.Client) *GetSCMOrgParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get s c m org params
func (o *GetSCMOrgParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredentialID adds the credentialID to the get s c m org params
func (o *GetSCMOrgParams) WithCredentialID(credentialID string) *GetSCMOrgParams {
	o.SetCredentialID(credentialID)
	return o
}

// SetCredentialID adds the credentialId to the get s c m org params
func (o *GetSCMOrgParams) SetCredentialID(credentialID string) {
	o.CredentialID = credentialID
}

// WithScm adds the scm to the get s c m org params
func (o *GetSCMOrgParams) WithScm(scm string) *GetSCMOrgParams {
	o.SetScm(scm)
	return o
}

// SetScm adds the scm to the get s c m org params
func (o *GetSCMOrgParams) SetScm(scm string) {
	o.Scm = scm
}

// WriteToRequest writes these params to a swagger request
func (o *GetSCMOrgParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param credentialId
	qrCredentialID := o.CredentialID
	qCredentialID := qrCredentialID
	if qCredentialID != "" {

		if err := r.SetQueryParam("credentialId", qCredentialID); err != nil {
			return err
		}
	}

	// path param scm
	if err := r.SetPathParam("scm", o.Scm); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
