// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_scm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/ks-devops-client-go/models"
)

// ListRepositoriesReader is a Reader for the ListRepositories structure.
type ListRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRepositoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha3/scms/{scm}/organizations/{organization}/repositories] listRepositories", response, response.Code())
	}
}

// NewListRepositoriesOK creates a ListRepositoriesOK with default headers values
func NewListRepositoriesOK() *ListRepositoriesOK {
	return &ListRepositoriesOK{}
}

/*
ListRepositoriesOK describes a response with status code 200, with default header values.

ok
*/
type ListRepositoriesOK struct {
	Payload *models.ScmRepositoryListResult
}

// IsSuccess returns true when this list repositories o k response has a 2xx status code
func (o *ListRepositoriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list repositories o k response has a 3xx status code
func (o *ListRepositoriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list repositories o k response has a 4xx status code
func (o *ListRepositoriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list repositories o k response has a 5xx status code
func (o *ListRepositoriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list repositories o k response a status code equal to that given
func (o *ListRepositoriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list repositories o k response
func (o *ListRepositoriesOK) Code() int {
	return 200
}

func (o *ListRepositoriesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/scms/{scm}/organizations/{organization}/repositories][%d] listRepositoriesOK %s", 200, payload)
}

func (o *ListRepositoriesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha3/scms/{scm}/organizations/{organization}/repositories][%d] listRepositoriesOK %s", 200, payload)
}

func (o *ListRepositoriesOK) GetPayload() *models.ScmRepositoryListResult {
	return o.Payload
}

func (o *ListRepositoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScmRepositoryListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
