// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenericWebhookParams creates a new GenericWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenericWebhookParams() *GenericWebhookParams {
	return &GenericWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenericWebhookParamsWithTimeout creates a new GenericWebhookParams object
// with the ability to set a timeout on a request.
func NewGenericWebhookParamsWithTimeout(timeout time.Duration) *GenericWebhookParams {
	return &GenericWebhookParams{
		timeout: timeout,
	}
}

// NewGenericWebhookParamsWithContext creates a new GenericWebhookParams object
// with the ability to set a context for a request.
func NewGenericWebhookParamsWithContext(ctx context.Context) *GenericWebhookParams {
	return &GenericWebhookParams{
		Context: ctx,
	}
}

// NewGenericWebhookParamsWithHTTPClient creates a new GenericWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenericWebhookParamsWithHTTPClient(client *http.Client) *GenericWebhookParams {
	return &GenericWebhookParams{
		HTTPClient: client,
	}
}

/*
GenericWebhookParams contains all the parameters to send to the API endpoint

	for the generic webhook operation.

	Typically these are written to a http.Request.
*/
type GenericWebhookParams struct {

	// Body.
	Body []int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generic webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenericWebhookParams) WithDefaults() *GenericWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generic webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenericWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generic webhook params
func (o *GenericWebhookParams) WithTimeout(timeout time.Duration) *GenericWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generic webhook params
func (o *GenericWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generic webhook params
func (o *GenericWebhookParams) WithContext(ctx context.Context) *GenericWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generic webhook params
func (o *GenericWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generic webhook params
func (o *GenericWebhookParams) WithHTTPClient(client *http.Client) *GenericWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generic webhook params
func (o *GenericWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generic webhook params
func (o *GenericWebhookParams) WithBody(body []int64) *GenericWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generic webhook params
func (o *GenericWebhookParams) SetBody(body []int64) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenericWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
