// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNotifyCommitReader is a Reader for the GetNotifyCommit structure.
type GetNotifyCommitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNotifyCommitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNotifyCommitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/devops.kubesphere.io/v1alpha2/webhook/git] GetNotifyCommit", response, response.Code())
	}
}

// NewGetNotifyCommitOK creates a GetNotifyCommitOK with default headers values
func NewGetNotifyCommitOK() *GetNotifyCommitOK {
	return &GetNotifyCommitOK{}
}

/*
GetNotifyCommitOK describes a response with status code 200, with default header values.

OK
*/
type GetNotifyCommitOK struct {
}

// IsSuccess returns true when this get notify commit o k response has a 2xx status code
func (o *GetNotifyCommitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get notify commit o k response has a 3xx status code
func (o *GetNotifyCommitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notify commit o k response has a 4xx status code
func (o *GetNotifyCommitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get notify commit o k response has a 5xx status code
func (o *GetNotifyCommitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get notify commit o k response a status code equal to that given
func (o *GetNotifyCommitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get notify commit o k response
func (o *GetNotifyCommitOK) Code() int {
	return 200
}

func (o *GetNotifyCommitOK) Error() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/webhook/git][%d] getNotifyCommitOK", 200)
}

func (o *GetNotifyCommitOK) String() string {
	return fmt.Sprintf("[GET /kapis/devops.kubesphere.io/v1alpha2/webhook/git][%d] getNotifyCommitOK", 200)
}

func (o *GetNotifyCommitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
