// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GithubWebhookReader is a Reader for the GithubWebhook structure.
type GithubWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GithubWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGithubWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/github] GithubWebhook", response, response.Code())
	}
}

// NewGithubWebhookOK creates a GithubWebhookOK with default headers values
func NewGithubWebhookOK() *GithubWebhookOK {
	return &GithubWebhookOK{}
}

/*
GithubWebhookOK describes a response with status code 200, with default header values.

ok
*/
type GithubWebhookOK struct {
	Payload []int64
}

// IsSuccess returns true when this github webhook o k response has a 2xx status code
func (o *GithubWebhookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this github webhook o k response has a 3xx status code
func (o *GithubWebhookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this github webhook o k response has a 4xx status code
func (o *GithubWebhookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this github webhook o k response has a 5xx status code
func (o *GithubWebhookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this github webhook o k response a status code equal to that given
func (o *GithubWebhookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the github webhook o k response
func (o *GithubWebhookOK) Code() int {
	return 200
}

func (o *GithubWebhookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/github][%d] githubWebhookOK %s", 200, payload)
}

func (o *GithubWebhookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/github][%d] githubWebhookOK %s", 200, payload)
}

func (o *GithubWebhookOK) GetPayload() []int64 {
	return o.Payload
}

func (o *GithubWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
