// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostNotifyCommitReader is a Reader for the PostNotifyCommit structure.
type PostNotifyCommitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostNotifyCommitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostNotifyCommitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/git] PostNotifyCommit", response, response.Code())
	}
}

// NewPostNotifyCommitOK creates a PostNotifyCommitOK with default headers values
func NewPostNotifyCommitOK() *PostNotifyCommitOK {
	return &PostNotifyCommitOK{}
}

/*
PostNotifyCommitOK describes a response with status code 200, with default header values.

ok
*/
type PostNotifyCommitOK struct {
	Payload []int64
}

// IsSuccess returns true when this post notify commit o k response has a 2xx status code
func (o *PostNotifyCommitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post notify commit o k response has a 3xx status code
func (o *PostNotifyCommitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post notify commit o k response has a 4xx status code
func (o *PostNotifyCommitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post notify commit o k response has a 5xx status code
func (o *PostNotifyCommitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post notify commit o k response a status code equal to that given
func (o *PostNotifyCommitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post notify commit o k response
func (o *PostNotifyCommitOK) Code() int {
	return 200
}

func (o *PostNotifyCommitOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/git][%d] postNotifyCommitOK %s", 200, payload)
}

func (o *PostNotifyCommitOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha2/webhook/git][%d] postNotifyCommitOK %s", 200, payload)
}

func (o *PostNotifyCommitOK) GetPayload() []int64 {
	return o.Payload
}

func (o *PostNotifyCommitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
