// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ScmWebhookReader is a Reader for the ScmWebhook structure.
type ScmWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScmWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewScmWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/devops.kubesphere.io/v1alpha3/webhooks/scm] scmWebhook", response, response.Code())
	}
}

// NewScmWebhookOK creates a ScmWebhookOK with default headers values
func NewScmWebhookOK() *ScmWebhookOK {
	return &ScmWebhookOK{}
}

/*
ScmWebhookOK describes a response with status code 200, with default header values.

ok
*/
type ScmWebhookOK struct {
	Payload []int64
}

// IsSuccess returns true when this scm webhook o k response has a 2xx status code
func (o *ScmWebhookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this scm webhook o k response has a 3xx status code
func (o *ScmWebhookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this scm webhook o k response has a 4xx status code
func (o *ScmWebhookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this scm webhook o k response has a 5xx status code
func (o *ScmWebhookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this scm webhook o k response a status code equal to that given
func (o *ScmWebhookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the scm webhook o k response
func (o *ScmWebhookOK) Code() int {
	return 200
}

func (o *ScmWebhookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha3/webhooks/scm][%d] scmWebhookOK %s", 200, payload)
}

func (o *ScmWebhookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/devops.kubesphere.io/v1alpha3/webhooks/scm][%d] scmWebhookOK %s", 200, payload)
}

func (o *ScmWebhookOK) GetPayload() []int64 {
	return o.Payload
}

func (o *ScmWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
