// Code generated by go-swagger; DO NOT EDIT.

package dev_ops_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewScmWebhookParams creates a new ScmWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScmWebhookParams() *ScmWebhookParams {
	return &ScmWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScmWebhookParamsWithTimeout creates a new ScmWebhookParams object
// with the ability to set a timeout on a request.
func NewScmWebhookParamsWithTimeout(timeout time.Duration) *ScmWebhookParams {
	return &ScmWebhookParams{
		timeout: timeout,
	}
}

// NewScmWebhookParamsWithContext creates a new ScmWebhookParams object
// with the ability to set a context for a request.
func NewScmWebhookParamsWithContext(ctx context.Context) *ScmWebhookParams {
	return &ScmWebhookParams{
		Context: ctx,
	}
}

// NewScmWebhookParamsWithHTTPClient creates a new ScmWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewScmWebhookParamsWithHTTPClient(client *http.Client) *ScmWebhookParams {
	return &ScmWebhookParams{
		HTTPClient: client,
	}
}

/*
ScmWebhookParams contains all the parameters to send to the API endpoint

	for the scm webhook operation.

	Typically these are written to a http.Request.
*/
type ScmWebhookParams struct {

	// Body.
	Body []int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scm webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScmWebhookParams) WithDefaults() *ScmWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scm webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScmWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scm webhook params
func (o *ScmWebhookParams) WithTimeout(timeout time.Duration) *ScmWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scm webhook params
func (o *ScmWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scm webhook params
func (o *ScmWebhookParams) WithContext(ctx context.Context) *ScmWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scm webhook params
func (o *ScmWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scm webhook params
func (o *ScmWebhookParams) WithHTTPClient(client *http.Client) *ScmWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scm webhook params
func (o *ScmWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scm webhook params
func (o *ScmWebhookParams) WithBody(body []int64) *ScmWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scm webhook params
func (o *ScmWebhookParams) SetBody(body []int64) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ScmWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
