// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DefaultParameterValue default parameter value
//
// swagger:model .defaultParameterValue
type DefaultParameterValue struct {

	// It’s a fully qualified name and is an identifier of the producer of this resource's capability.
	Class string `json:"_class,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// value, string or bool type
	Value DefaultParameterValueValue `json:"value,omitempty"`
}

// Validate validates this default parameter value
func (m *DefaultParameterValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this default parameter value based on context it is used
func (m *DefaultParameterValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefaultParameterValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefaultParameterValue) UnmarshalBinary(b []byte) error {
	var res DefaultParameterValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
