// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DevopsCheckScript devops check script
//
// swagger:model devops.CheckScript
type DevopsCheckScript struct {

	// column e.g. 0
	Column int32 `json:"column,omitempty"`

	// line e.g. 0
	Line int32 `json:"line,omitempty"`

	// message e.g. unexpected char: '#'
	Message string `json:"message,omitempty"`

	// status e.g. fail
	Status string `json:"status,omitempty"`
}

// Validate validates this devops check script
func (m *DevopsCheckScript) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this devops check script based on context it is used
func (m *DevopsCheckScript) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DevopsCheckScript) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DevopsCheckScript) UnmarshalBinary(b []byte) error {
	var res DevopsCheckScript
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
