// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DevopsRunPipelineDescription devops run pipeline description
//
// swagger:model devops.RunPipeline.description
type DevopsRunPipelineDescription interface{}
