// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DevopsRunPipelineRunSummary devops run pipeline run summary
//
// swagger:model devops.RunPipeline.runSummary
type DevopsRunPipelineRunSummary interface{}
