// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DevopsBranch devops branch
//
// swagger:model devops.Branch
type DevopsBranch struct {

	// name
	Name string `json:"Name,omitempty"`

	// s h a1
	SHA1 string `json:"SHA1,omitempty"`
}

// Validate validates this devops branch
func (m *DevopsBranch) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this devops branch based on context it is used
func (m *DevopsBranch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DevopsBranch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DevopsBranch) UnmarshalBinary(b []byte) error {
	var res DevopsBranch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
