// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DevopsBranchPipelineParametersChoices devops branch pipeline parameters choices
//
// swagger:model devops.BranchPipeline.parameters.choices
type DevopsBranchPipelineParametersChoices interface{}
