// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DevopsBranchPipelineParameters devops branch pipeline parameters
//
// swagger:model devops.BranchPipeline.parameters
type DevopsBranchPipelineParameters struct {

	// It’s a fully qualified name and is an identifier of the producer of this resource's capability.
	Class string `json:"_class,omitempty"`

	// choices
	Choices []DevopsBranchPipelineParametersChoices `json:"choices"`

	// default parameter value
	DefaultParameterValue *DefaultParameterValue `json:"defaultParameterValue,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this devops branch pipeline parameters
func (m *DevopsBranchPipelineParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefaultParameterValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DevopsBranchPipelineParameters) validateDefaultParameterValue(formats strfmt.Registry) error {
	if swag.IsZero(m.DefaultParameterValue) { // not required
		return nil
	}

	if m.DefaultParameterValue != nil {
		if err := m.DefaultParameterValue.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("defaultParameterValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("defaultParameterValue")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this devops branch pipeline parameters based on the context it is used
func (m *DevopsBranchPipelineParameters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDefaultParameterValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DevopsBranchPipelineParameters) contextValidateDefaultParameterValue(ctx context.Context, formats strfmt.Registry) error {

	if m.DefaultParameterValue != nil {

		if swag.IsZero(m.DefaultParameterValue) { // not required
			return nil
		}

		if err := m.DefaultParameterValue.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("defaultParameterValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("defaultParameterValue")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DevopsBranchPipelineParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DevopsBranchPipelineParameters) UnmarshalBinary(b []byte) error {
	var res DevopsBranchPipelineParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
