// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DevopsRunPipelineChangeSet devops run pipeline change set
//
// swagger:model devops.RunPipeline.changeSet
type DevopsRunPipelineChangeSet interface{}
