// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DevopsBranchPipelineRunNodesFirstParent devops branch pipeline run nodes first parent
//
// swagger:model devops.BranchPipelineRunNodes.firstParent
type DevopsBranchPipelineRunNodesFirstParent interface{}
