// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobPullRequest job pull request
//
// swagger:model job.PullRequest
type JobPullRequest struct {

	// author
	Author string `json:"author,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this job pull request
func (m *JobPullRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job pull request based on context it is used
func (m *JobPullRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobPullRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobPullRequest) UnmarshalBinary(b []byte) error {
	var res JobPullRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
