// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PipelineCause pipeline cause
//
// swagger:model pipeline.Cause
type PipelineCause struct {

	// short description
	ShortDescription string `json:"shortDescription,omitempty"`
}

// Validate validates this pipeline cause
func (m *PipelineCause) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pipeline cause based on context it is used
func (m *PipelineCause) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineCause) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineCause) UnmarshalBinary(b []byte) error {
	var res PipelineCause
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
