// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ScmSource scm source
//
// swagger:model .scmSource
type ScmSource struct {

	// It’s a fully qualified name and is an identifier of the producer of this resource's capability.
	Class string `json:"_class,omitempty"`

	// api url
	APIURL ScmSourceAPIURL `json:"apiUrl,omitempty"`

	// The id of the source configuration management (SCM).
	ID string `json:"id,omitempty"`
}

// Validate validates this scm source
func (m *ScmSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scm source based on context it is used
func (m *ScmSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScmSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScmSource) UnmarshalBinary(b []byte) error {
	var res ScmSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
