// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScmRepository scm repository
//
// swagger:model scm.repository
type ScmRepository struct {

	// default branch
	// Required: true
	DefaultBranch *string `json:"defaultBranch"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this scm repository
func (m *ScmRepository) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefaultBranch(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScmRepository) validateDefaultBranch(formats strfmt.Registry) error {

	if err := validate.Required("defaultBranch", "body", m.DefaultBranch); err != nil {
		return err
	}

	return nil
}

func (m *ScmRepository) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this scm repository based on context it is used
func (m *ScmRepository) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScmRepository) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScmRepository) UnmarshalBinary(b []byte) error {
	var res ScmRepository
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
