// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1S2iBinaryStatus v1alpha1 s2i binary status
//
// swagger:model v1alpha1.S2iBinaryStatus
type V1alpha1S2iBinaryStatus struct {

	// phase
	Phase string `json:"phase,omitempty"`
}

// Validate validates this v1alpha1 s2i binary status
func (m *V1alpha1S2iBinaryStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 s2i binary status based on context it is used
func (m *V1alpha1S2iBinaryStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1S2iBinaryStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1S2iBinaryStatus) UnmarshalBinary(b []byte) error {
	var res V1alpha1S2iBinaryStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
