// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha3DevOpsProjectStatus v1alpha3 dev ops project status
//
// swagger:model v1alpha3.DevOpsProjectStatus
type V1alpha3DevOpsProjectStatus struct {

	// admin namespace
	AdminNamespace string `json:"adminNamespace,omitempty"`
}

// Validate validates this v1alpha3 dev ops project status
func (m *V1alpha3DevOpsProjectStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha3 dev ops project status based on context it is used
func (m *V1alpha3DevOpsProjectStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha3DevOpsProjectStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha3DevOpsProjectStatus) UnmarshalBinary(b []byte) error {
	var res V1alpha3DevOpsProjectStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
