// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha3DiscoverPRFromForks v1alpha3 discover p r from forks
//
// swagger:model v1alpha3.DiscoverPRFromForks
type V1alpha3DiscoverPRFromForks struct {

	// github discover strategy
	Strategy int32 `json:"strategy,omitempty"`

	// trust user type
	Trust int32 `json:"trust,omitempty"`
}

// Validate validates this v1alpha3 discover p r from forks
func (m *V1alpha3DiscoverPRFromForks) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha3 discover p r from forks based on context it is used
func (m *V1alpha3DiscoverPRFromForks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha3DiscoverPRFromForks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha3DiscoverPRFromForks) UnmarshalBinary(b []byte) error {
	var res V1alpha3DiscoverPRFromForks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
