// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha3SvnSource v1alpha3 svn source
//
// swagger:model v1alpha3.SvnSource
type V1alpha3SvnSource struct {

	// credential id to access svn source
	CredentialID string `json:"credential_id,omitempty"`

	// branches do not run pipeline
	Excludes string `json:"excludes,omitempty"`

	// branches to run pipeline
	Includes string `json:"includes,omitempty"`

	// remote address url
	Remote string `json:"remote,omitempty"`

	// uid of scm
	ScmID string `json:"scm_id,omitempty"`
}

// Validate validates this v1alpha3 svn source
func (m *V1alpha3SvnSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha3 svn source based on context it is used
func (m *V1alpha3SvnSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha3SvnSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha3SvnSource) UnmarshalBinary(b []byte) error {
	var res V1alpha3SvnSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
