// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1alpha3SignatureKey v1alpha3 signature key
//
// swagger:model v1alpha3.SignatureKey
type V1alpha3SignatureKey struct {

	// key ID
	// Required: true
	KeyID *string `json:"keyID"`
}

// Validate validates this v1alpha3 signature key
func (m *V1alpha3SignatureKey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha3SignatureKey) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("keyID", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1alpha3 signature key based on context it is used
func (m *V1alpha3SignatureKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha3SignatureKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha3SignatureKey) UnmarshalBinary(b []byte) error {
	var res V1alpha3SignatureKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
