// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1alpha3PipelineStatus v1alpha3 pipeline status
//
// swagger:model v1alpha3.PipelineStatus
type V1alpha3PipelineStatus interface{}
