// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha3GitRepositoryStatus v1alpha3 git repository status
//
// swagger:model v1alpha3.GitRepositoryStatus
type V1alpha3GitRepositoryStatus struct {

	// connection
	Connection string `json:"connection,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this v1alpha3 git repository status
func (m *V1alpha3GitRepositoryStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha3 git repository status based on context it is used
func (m *V1alpha3GitRepositoryStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha3GitRepositoryStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha3GitRepositoryStatus) UnmarshalBinary(b []byte) error {
	var res V1alpha3GitRepositoryStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
